# Dependabot configuration
# Automated dependency updates with security prioritization

version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    target-branch: "develop"
    reviewers:
      - "terragon-labs"
    assignees:
      - "terragon-labs"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    target-branch: "develop"
    reviewers:
      - "terragon-labs"
    assignees:
      - "terragon-labs"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 3
    rebase-strategy: "auto"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    target-branch: "develop"
    reviewers:
      - "terragon-labs"
    assignees:
      - "terragon-labs"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
    open-pull-requests-limit: 3
    rebase-strategy: "auto"