name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen.
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear description of what actually happened.
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Please provide details about your environment
      value: |
        - OS: [e.g., Ubuntu 22.04, macOS 13.0, Windows 11]
        - Python Version: [e.g., 3.11.5]
        - LLM Cost Tracker Version: [e.g., 0.1.0]
        - Docker Version: [e.g., 24.0.6] (if applicable)
        - Browser: [e.g., Chrome 118.0.5993.70] (if applicable)
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please include any relevant log outputs, error messages, or stack traces
      placeholder: Paste logs here...
      render: shell

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Please share relevant configuration (remove sensitive information)
      placeholder: |
        # pyproject.toml snippet
        # Environment variables (without secrets)
        # docker-compose.yml snippet
      render: yaml

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - "Low - Minor issue that doesn't affect core functionality"
        - "Medium - Issue affects some functionality but has workarounds"
        - "High - Issue significantly impacts functionality"
        - "Critical - Issue causes system failure or data loss"
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - "Cost Tracking"
        - "OpenTelemetry Integration"
        - "Budget Management"
        - "Alerting System"
        - "Database"
        - "API"
        - "Documentation"
        - "Docker/Deployment"
        - "Monitoring/Grafana"
        - "Security"
        - "Other"
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I have provided all requested information
          required: true
        - label: I have removed or masked any sensitive information from logs/config
          required: true
        - label: I am willing to help test fixes for this bug
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - Screenshots or videos (if applicable)
        - Related issues or pull requests
        - Potential solutions you've considered
        - Impact on your use case